language: c
dist: xenial
script: make
compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6 libxfixes-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
