language: cpp
dist: xenial
script: make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libxfixes-dev
      - mesa-common-dev
      - libasound2-dev
      - libgl1-mesa-dev

matrix:
  include:
    - name: gcc-release
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - name: clang-release
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - name: win64-release
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - mkdir build
        - cd build
        - cmake -G "Visual Studio 15 2017" -Ax64 ..
        - cmake --build . --config Release

before_install:
    - eval "${MATRIX_EVAL}"
