language: c
dist: xenial
script: make
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libxfixes-dev
      - mesa-common-dev
      - libasound2-dev
      - libgl1-mesa-dev

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
