language: cpp
dist: xenial
script: make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libxfixes-dev
      - mesa-common-dev
      - libasound2-dev
      - libgl1-mesa-dev

matrix:
  include:
    - name: gcc-release
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - name: clang-release
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - name: win64-release
      os: windows
      install:
        - choco install -y windows-sdk-10.1 --version 10.1.17763.1
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - msbuild.exe stameska.sln -p:Configuration=Release -p:Platform=x64 -t:stameska

before_install:
    - eval "${MATRIX_EVAL}"
