/* File generated with Shader Minifier 1.1.4
 * http://www.ctrl-alt-test.fr
 */
#ifndef INTRO_H_
# define INTRO_H_

const char *intro_glsl =
 "uniform vec2 R;"
 "uniform sampler2D T;"
 "uniform int s;"
 "float v=float(s)/88200.;"
 "const vec3 m=vec3(0.,.001,1.);"
 "const float i=3.14159;"
 "float n(float v)"
 "{"
   "return fract(sin(v)*43758.5);"
 "}"
 "float f(vec2 y)"
 "{"
   "return n(dot(y,vec2(129.47,37.56)));"
 "}"
 "float x(vec2 v)"
 "{"
   "vec2 y=floor(v);"
   "v=fract(v);"
   "v*=v*(3.-2.*v);"
   "return mix(mix(f(y),f(y+m.zx),v.x),mix(f(y+m.xz),f(y+m.zz),v.x),v.y);"
 "}"
 "float t(vec2 v)"
 "{"
   "return.5*x(v)+.25*x(v*2.3)+.125*x(v*4.1);"
 "}"
 "float f(vec3 v,vec3 y)"
 "{"
   "return v=abs(v)-y,max(v.z,max(v.x,v.y));"
 "}"
 "mat3 p(float v)"
 "{"
   "float y=sin(v),z=cos(v);"
   "return mat3(1.,0.,0.,0.,z,-y,0.,y,z);"
 "}"
 "mat3 e(float v)"
 "{"
   "float y=sin(v),z=cos(v);"
   "return mat3(z,0.,y,0.,1.,0,-y,0.,z);"
 "}"
 "mat3 r(float v)"
 "{"
   "float y=sin(v),z=cos(v);"
   "return mat3(z,y,0.,-y,z,0.,0.,0.,1.);"
 "}"
 "int d=1;"
 "float z,y;"
 "float c(vec3 v)"
 "{"
   "if(d==1)"
     "{"
       "z=v.y;"
       "y=min(v.x+4.,6.-v.y);"
       "vec3 m=v;"
       "m.z=mod(v.z,10.)-5.;"
       "float i=f(m,vec3(1.,10.,1.));"
       "m.x-=4.;"
       "m.y+=-1.5;"
       "float x=f(m,vec3(.5,10.,.5));"
       "y=min(y,x);"
       "y=min(y,f(v-vec3(5.,0.,0.),vec3(1.,1.,100.)));"
       "y=max(y,-min(i,6.4-v.y));"
       "y=max(y,v.x-6.);"
       "y=min(y,v.z+30.);"
       "z=max(z,v.x-6.);"
       "return min(z,y);"
     "}"
   "else"
     " if(d==3)"
       "{"
         "z=v.y;"
         "z=min(z,f(v,vec3(.3,.1,30.)));"
         "y=-f(v,vec3(3.,4.,30.));"
         "vec3 m=v;"
         "m.z=mod(v.z,10.)-5.;"
         "m.x-=3.;"
         "m.y+=-1.5;"
         "y=max(y,-f(m,vec3(2.,1.2,1.)));"
         "y=max(y,v.x-4.4);"
         "return min(z,y);"
       "}"
     "else"
       " if(d==7)"
         "return z=v.y,y=v.z+30.,v.x=abs(v.x),y=min(y,10.-v.x),y=min(y,f(v-vec3(14.,12.,-20.),vec3(8.,4.,10.))),min(z,y);"
   "return min(v.y+1.,length(v)-1.);"
 "}"
 "vec3 a(vec3 v)"
 "{"
   "return normalize(vec3(c(v+m.yxx)-c(v-m.yxx),c(v+m.xyx)-c(v-m.xyx),c(v+m.xxy)-c(v-m.xxy)));"
 "}"
 "float a(vec3 v,vec3 y,float z,float x,int m)"
 "{"
   "for(int f=0;f<m;++f)"
     "{"
       "float i=c(v+y*z);"
       "z+=i;"
       "if(i<.002*z||z>x)"
         "break;"
     "}"
   "return z;"
 "}"
 "float l(vec2 v)"
 "{"
   "return t(v*16.+8.*(vec2(t(v*4.),t(v*4.+96.))-.5));"
 "}"
 "vec3 h(vec2 v)"
 "{"
   "v*=4.;"
   "vec3 y=(.6+(.2+.2*smoothstep(.9,.99,sin(i*t(v))))*t(v*4.))*vec3(.753,.749,.733);"
   "return y;"
 "}"
 "vec3 w(vec2 v)"
 "{"
   "return mix(vec3(.467,.22,.1),vec3(.627,.35,.216),smoothstep(.2,.8,t(v*3.)));"
 "}"
 "vec2 a(vec3 v,vec3 y)"
 "{"
   "vec3 z=cross(y,m.zxx),x=cross(y,m.xxz),i,f;"
   "if(dot(z,z)>dot(x,x))"
     "i=z;"
   "else"
     " i=x;"
   "f=cross(y,i);"
   "return vec2(dot(v,f),dot(v,i)).xy;"
 "}"
 "void main()"
 "{"
   "vec2 m=gl_FragCoord.xy/R*2.-1.;"
   "m.x*=2.*R.x/R.y;"
   "vec3 i,x,d;"
   "i=vec3(-.5+.5*sin(v/16.),1.8,5.);"
   "x=normalize(vec3(m,-2.));"
   "vec3 r=normalize(vec3(m+vec2(2.,1.)/R,-2.));"
   "x=p(-.2)*x;"
   "r=p(-.2)*r;"
   "vec3 c=normalize(vec3(-2.,1.,1.));"
   "float l=.2;"
   "const int k=16;"
   "float e=v;"
   "vec3 g=vec3(0.);"
   "for(int u=0;u<k;++u)"
     "{"
       "vec3 o=i,b=mix(x,r,vec3(n(e),n(e+1.),n(e+2.))),C=vec3(0.),D=vec3(1.);"
       "for(int Z=0;Z<3;++Z)"
         "{"
           "float Y=60.;"
           "int X=0;"
           "float W=min(Y,50.),V=a(o,b,0.,W,40);"
           "if(V<W)"
             "Y=V,X=2;"
           "vec3 U=vec3(0.),S,Q=vec3(0.,1.,0.);"
           "float P=.04;"
           "P=.9;"
           "if(X==0)"
             "U=vec3(2.)+30.*pow(max(0.,dot(b,c)),10.),S=vec3(0.);"
           "else"
             "{"
               "o=o+b*Y;"
               "Q=a(o);"
               "vec2 O=a(o,Q);"
               "o+=Q*.01;"
               "if(z<y)"
                 "{"
                   "S=vec3(.75,.75,.73);"
                   "float M=t(O/4.);"
                   "S=mix(S,vec3(.3,.44,.15)*(.3+.7*t(O*16.)),smoothstep(.45,.6,M));"
                   "float L=smoothstep(.4,.45,t(O/2.));"
                   "P=9.*L+.01;"
                 "}"
               "else"
                 "{"
                   "S=h(O);"
                   "vec2 M=floor(O/2.),L=O/2.-M;"
                   "float K=f(M);"
                   "S*=1.-.3*K-.4*step(.99,max(L.x,L.y));"
                   "S=mix(S,.6*w(O),1.-step(.5,max(L.x,L.y)));"
                   "S=mix(S,.4*w(O)*(.3+.7*t(O*vec2(16.,4.))),smoothstep(.5,.6,t(O*vec2(1.,.2))));"
                   "float J=t(O/4.),I=smoothstep(.5,.7,J);"
                   "S=mix(S,vec3(.3,.44,.15)*(.3+.7*t(O*16.)),I);"
                 "}"
             "}"
           "C+=D*U;"
           "D*=S.xyz;"
           "if(all(lessThan(D,vec3(.003))))"
             "break;"
           "b=reflect(b,Q);"
           "b=normalize(mix(b,(vec3(n(e+=b.x),n(e+=b.y),n(e+=b.z))-.5)*2.,P));"
           "b*=sign(dot(Q,b));"
         "}"
       "g+=C;"
     "}"
   "gl_FragColor=vec4(g/float(k),l);"
 "}";

#endif // INTRO_H_
