/* File generated with Shader Minifier 1.1.4
 * http://www.ctrl-alt-test.fr
 */
#ifndef INTRO_H_
# define INTRO_H_

const char *intro_glsl =
 "#version 130\n"
 "uniform vec2 RES;"
 "uniform float t;"
 "uniform sampler2D N;"
 "const vec3 v=vec3(0.,.001,1.);"
 "const float m=3.14159;"
 "float i=t/8.,f=t/16.,x=t/32.,y=t/64.;"
 "float n(float v)"
 "{"
   "return fract(sin(v)*43758.5);"
 "}"
 "float p(vec2 v)"
 "{"
   "return n(dot(v,vec2(129.47,37.56)));"
 "}"
 "float e(vec2 f)"
 "{"
   "vec2 m=floor(f);"
   "f=fract(f);"
   "return mix(mix(p(m),p(m+v.zx),f.x),mix(p(m+v.xz),p(m+v.zz),f.x),f.y);"
 "}"
 "float s(vec2 v)"
 "{"
   "return.5*e(v)+.25*e(v*2.3)+.125*e(v*4.1);"
 "}"
 "vec4 r(vec2 v)"
 "{"
   "return texture2D(N,v);"
 "}"
 "vec4 d(vec2 v)"
 "{"
   "return texture2D(N,(v+.5)/textureSize(N,0));"
 "}"
 "vec3 d(vec3 v,vec3 f)"
 "{"
   "return mod(v,f)-f*.5;"
 "}"
 "float o(vec3 v)"
 "{"
   "return max(v.x,max(v.y,v.z));"
 "}"
 "float e(vec3 v,vec3 m)"
 "{"
   "return o(abs(v)-m);"
 "}"
 "mat3 h(float v)"
 "{"
   "float f=sin(v),x=cos(v);"
   "return mat3(1.,0.,0.,0.,x,-f,0.,f,x);"
 "}"
 "mat3 R(float v)"
 "{"
   "float f=sin(v),x=cos(v);"
   "return mat3(x,0.,f,0.,1.,0,-f,0.,x);"
 "}"
 "mat3 D(float v)"
 "{"
   "float f=sin(v),x=cos(v);"
   "return mat3(x,f,0.,-f,x,0.,0.,0.,1.);"
 "}"
 "float D(float v,float f,float x)"
 "{"
   "vec2 m=max(vec2(x-v,x-f),vec2(0));"
   "return max(x,min(v,f))-length(m);"
 "}"
 "mat3 R(vec3 v,vec3 f,vec3 x)"
 "{"
   "vec3 m=normalize(v-f),y=normalize(cross(x,m));"
   "x=normalize(cross(m,y));"
   "return mat3(y,x,m);"
 "}"
 "float z=6.36e+06,l=6.38e+06,S=40.;"
 "vec3 k=vec3(0.,-z,0.),c=vec3(5.8e-06,1.35e-05,3.31e-05),g=vec3(2e-05),a=g*1.1,u;"
 "vec2 w(vec3 v)"
 "{"
   "float f=max(0.,length(v-k)-z);"
   "return vec2(exp(-f/8000.),exp(-f/1200.));"
 "}"
 "float d(vec3 v,vec3 f,float x)"
 "{"
   "vec3 m=v-k;"
   "float e=dot(m,f),y=dot(m,m)-x*x,i=e*e-y;"
   "if(i<0.)"
     "return-1.;"
   "i=sqrt(i);"
   "float n=-e-i,l=-e+i;"
   "return n>=0.?n:l;"
 "}"
 "vec2 D(vec3 v,vec3 f,float m,float x)"
 "{"
   "vec2 i=vec2(0.);"
   "m/=x;"
   "f*=m;"
   "for(float y=0.;y<x;++y)"
     "i+=w(v+f*y);"
   "return i*m;"
 "}"
 "vec3 R(vec3 v,vec3 f,float m,vec3 x)"
 "{"
   "vec2 i=vec2(0.);"
   "vec3 y,r;"
   "y=r=vec3(0.);"
   "float z=dot(f,u),s=8.;"
   "m/=s;"
   "f*=m;"
   "for(float e=0.;e<s;++e)"
     "{"
       "vec3 n=v+f*e;"
       "vec2 k=w(n)*m;"
       "i+=k;"
       "vec2 b=i;"
       "float p=d(n,u,l);"
       "b+=D(n,u,p,8.);"
       "vec3 C=exp(-c*b.x-a*b.y);"
       "y+=C*k.x;"
       "r+=C*k.y;"
     "}"
   "return x*exp(-c*i.x-a*i.y)+S*(1.+z*z)*(y*c*.0597+r*g*.0196/pow(1.58-1.52*z,1.5));"
 "}"
 "float E(vec3 m)"
 "{"
   "return m.y+=.2,min(length(m-v.zxx*1.5)-.8,length(m+v.zxx*1.5)-.8);"
 "}"
 "vec3 b=vec3(8.,4.,8.);"
 "float C=0.;"
 "float T(vec3 v)"
 "{"
   "v-=vec3(0.,b.y-1.,4.);"
   "float f=-e(v,b);"
   "if(t>768.)"
     "{"
       "f=max(f,e(v,b+1.));"
       "float m=e(v-u*b,vec3(C));"
       "f=max(f,-m);"
     "}"
   "return f;"
 "}"
 "mat3 q=h(y)*R(x);"
 "float Z(vec3 v)"
 "{"
   "return e(q*(v-vec3((t-320.)*3./256.-1.5,-.2,0.)),vec3(.3));"
 "}"
 "float Y(vec3 v)"
 "{"
   "float f=E(v);"
   "if(t>320.&&t<576.)"
     "f=D(f,Z(v),.3);"
   "return min(T(v),f);"
 "}"
 "vec3 X(vec3 m)"
 "{"
   "return normalize(vec3(Y(m+v.yxx)-Y(m-v.yxx),Y(m+v.xyx)-Y(m-v.xyx),Y(m+v.xxy)-Y(m-v.xxy)));"
 "}"
 "float D(vec3 v,vec3 f,float m,float x,int y)"
 "{"
   "float i=1.;"
   "for(int r=0;r<y;++r)"
     "{"
       "float n=Y(v+f*m);"
       "m+=n*i;"
       "if(n<.001*m||m>x)"
         "break;"
     "}"
   "return m;"
 "}"
 "void main()"
 "{"
   "vec2 f=gl_FragCoord.xy/RES*2.-1.;"
   "f.x*=2.*RES.x/RES.y;"
   "vec3 m=vec3(0.,1.5,3.9),x=v.xzx,i=vec3(0.),y=normalize(vec3(f,-2.));"
   "if(t<384.)"
     "{"
       "float z=smoothstep(64.,384.,t);"
       "i=mix(vec3(0.,.4,-4.),vec3(0.),z);"
       "m=mix(vec3(0.,.4,-3.),vec3(0.,1.5,3.9),z);"
     "}"
   "if(t>512.)"
     "{"
       "float z=smoothstep(512.,640.,t);"
       "m=mix(m,vec3(0.,-.2,5.9),z);"
       "float e=smoothstep(608.,768.,t);"
       "b=mix(b,vec3(2.4,3.,6.),e);"
       "C=mix(1.,5.,smoothstep(768.,896.,t));"
     "}"
   "y=R(m,i,x)*y;"
   "u=vec3(0.,1.,0.);"
   "const int z=16;"
   "float e=t;"
   "vec3 r=vec3(0.);"
   "for(int k=0;k<z;++k)"
     "{"
       "vec3 c=m,p=y,g=vec3(0.),a=vec3(1.);"
       "for(int S=0;S<4;++S)"
         "{"
           "float w=d(c,p,l);"
           "int Y=0;"
           "float q=w,Z=min(q,40.),h=D(c,p,0.,Z,32);"
           "if(h<Z)"
             "q=h,Y=2;"
           "vec3 o=vec3(0.),W=vec3(.75,.75,.73),V=vec3(0.,1.,0.);"
           "float U=.04;"
           "if(Y==0)"
             "{"
               "o=R(c,p,q,vec3(0.));"
               "if(any(isnan(o)))"
                 "{"
                   "return;"
                 "}"
               "W=vec3(0.);"
               "c=c+p*q;"
             "}"
           "else"
             "{"
               "c=c+p*q;"
               "if(Y==1)"
                 "{"
                   "float Q=smoothstep(.4,.5,s(c.xz*2.));"
                   "U=.02+.2*Q;"
                 "}"
               "else"
                 " if(Y==2)"
                   "{"
                     "V=X(c);"
                     "c+=V*.01;"
                     "if(T(c)>E(c))"
                       "U=.04;"
                     "else"
                       "{"
                         "U=.8;"
                         "if(V.z>.9)"
                           "{"
                             "vec2 Q=floor(c.xy*4.);"
                             "vec4 P=d(Q.yy*4.);"
                             "float O=mod(-t/2.+P.x*64.,64.)-32.;"
                             "o=vec3(step(O,Q.x)*step(Q.x,O+1.+8.*P.y));"
                           "}"
                         "else"
                           " if(V.y>.9)"
                             "{"
                               "vec4 Q=d(c.xz*8.),P=d(c.xz*4.+(Q.xy-.5)*2.);"
                               "U=.01+.8*P.x;"
                             "}"
                       "}"
                   "}"
                 "else"
                   " if(Y==3)"
                     "V=normalize(c);"
             "}"
           "g+=a*o;"
           "a*=W.xyz;"
           "if(all(lessThan(a,vec3(.001))))"
             "break;"
           "p=reflect(p,V);"
           "p=normalize(mix(p,(vec3(n(e+=p.x),n(e+=p.y),n(e+=p.z))-.5)*2.,U));"
           "p*=sign(dot(V,p));"
         "}"
       "r+=g;"
     "}"
   "r/=float(z);"
   "float p=.15;"
   "gl_FragColor=vec4(r,p);"
 "}";

#endif // INTRO_H_
